//Run this file with node ./knex/logSQLQuery.js to get the SQL generated by the knex function

const knex = require("knex");

function run(knex) {
    //replace this up to the, leaving the .toString()
    return knex.schema.createTable('categories', function (table) {
        table.increments('id').primary()
        table.string('name').notNullable();
    }).toString()
}

console.log(run(knex))
